name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: your-project-id
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    # Build & push commands
    - name: Build Docker image
      run: docker build -t gcr.io/your-project-id/flaskwebhook .

    - name: Push Docker image
      run: docker push gcr.io/your-project-id/flaskwebhook

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flask-webhook \
          --image gcr.io/your-project-id/flaskwebhook \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated